# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Travis Jacobs
tagline:          'Blog edition'
description:      ''
url:              http://travs.github.io/

author:
  name:           'Travis Jacobs'
  url:            http://travs.github.io/

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/travs/travs.github.io
