# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Travis Jacobs
tagline:          It's Now.
url:
paginate:         1
baseurl:          /
author:
  name:           Travis Jacobs
  url:            https://twitter.com/mdo
  email:          trav221@gmail.com

# Custom vars
version:          1.0.0
github:           https://github.com/travs

#Automatically require these gems

