# General Jekyll Config
url: http://travs.github.io/
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
